2021-03-25 Update
Re-Volt-America/rva_pack pull request #4
Opened 2021-03-25 21:01 UTC by EstebanMz

- Change package name to "rva"
- Some brackets were reordered
- Updated event date to tonight's lobby

2021-03-26 17:03 UTC, BGMP reviewed
Now that I see the hardcoded event date, I really do believe this is not the place for the pack's .json reference to be stored at.

Any comments on that? Because if indeed we were to store it in here, a new commit must be pushed every day updating the event's date for the night's session.

2021-03-26 20:04 UTC, BGMP commented
@Poputrash @Y100XTT Ideas?

2021-03-26 20:14 UTC, Poputrash commented
I believe a daily schedule is unnecesary. Perhaps if it was monthly, it
would justify the amount of work required. I think this last one is the
safest bet, because is more work to move files to another repository
instead of simply modifying the schedule.
You can post a monthly schedule for events and such, and refer people to
the discord channel for details.



On Fri, Mar 26, 2021, 17:05 José Benavente ***@***.***> wrote:

> @Poputrash <https://github.com/Poputrash> @Y100XTT
> <https://github.com/Y100XTT> Ideas?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Re-Volt-America/rva/pull/4#issuecomment-808479940>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATLNK6E5EFKTHUELLS23IVTTFTSHDANCNFSM4Z2DYTHA>
> .
>

2021-03-26 23:05 UTC, EstebanMz commented
If hosts were decided for a whole week and we only had to edit this file once per week it might be worthy to do this effort, as it happen at Re-Volt I/O, but it seems it is not the case in RVA. Honestly, I'd added the event feature to repo just because it was documented how to do it XD.
I vote to delete all the code related to events and only let the pack download through launcher.

2021-03-28 00:23 UTC, BGMP requested changes

2021-03-28 00:23 UTC, BGMP commented on rva-repo.json
>              },
```suggestion
```

2021-03-28 00:23 UTC, BGMP commented on rva-repo.json
>              },
Remove the hosts section for now, I guess. We may automate/better organise for this feature eventually

2021-03-28 00:34 UTC, BGMP approved these changes

2021-03-28 00:35 UTC, BGMP commented
Should be good to go!

2021-03-28 00:35 UTC, merged